### ISSUE TITLE
please publish a version have javascript!

### ISSUE THREAD

**Issue by sjbwylbs** [stomp-js/ng2-stompjs#26]
i got a issue .
You can test this [repo](https://github.com/sjbwylbs/ionic-ng2-stompjs)!
With ionic build --prod

Error: ./node_modules/@stomp/ng2-stompjs/src/stomp.service.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/Users/sjbwybls/Documents/gitrepo/ionic-ng2-stompjs/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
    at Object.loader (/Users/sjbwybls/Documents/gitrepo/ionic-ng2-stompjs/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
 @ ./src/app/app.module.ngfactory.js 45:0-65
 @ ./src/app/main.ts,./node_modules/@stomp/ng2-stompjs/src/stomp.config.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/Users/sjbwybls/Documents/gitrepo/ionic-ng2-stompjs/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
    at Object.loader (/Users/sjbwybls/Documents/gitrepo/ionic-ng2-stompjs/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
 @ ./src/app/app.module.ngfactory.js 66:0-64
 @ ./src/app/main.ts,./node_modules/@stomp/ng2-stompjs/index.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/Users/sjbwybls/Documents/gitrepo/ionic-ng2-stompjs/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
    at Object.loader (/Users/sjbwybls/Documents/gitrepo/ionic-ng2-stompjs/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
 @ ./src/app/app.module.js 15:0-63
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts
[DEBUG] Error: ./node_modules/@stomp/ng2-stompjs/src/stomp.service.ts
        Module build failed: TypeError: Cannot read property 'content' of undefined
            at Object.optimizationLoader
        (/Users/sjbwybls/Documents/gitrepo/ionic-ng2-stompjs/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
            at Object.loader
        (/Users/sjbwybls/Documents/gitrepo/ionic-ng2-stompjs/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
        @ ./src/app/app.module.ngfactory.js 45:0-65
        @ ./src/app/main.ts,./node_modules/@stomp/ng2-stompjs/src/stomp.config.ts
        Module build failed: TypeError: Cannot read property 'content' of undefined
            at Object.optimizationLoader
        (/Users/sjbwybls/Documents/gitrepo/ionic-ng2-stompjs/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
            at Object.loader
        (/Users/sjbwybls/Documents/gitrepo/ionic-ng2-stompjs/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
        @ ./src/app/app.module.ngfactory.js 66:0-64
        @ ./src/app/main.ts,./node_modules/@stomp/ng2-stompjs/index.ts
        Module build failed: TypeError: Cannot read property 'content' of undefined
            at Object.optimizationLoader
        (/Users/sjbwybls/Documents/gitrepo/ionic-ng2-stompjs/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
            at Object.loader
        (/Users/sjbwybls/Documents/gitrepo/ionic-ng2-stompjs/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
        @ ./src/app/app.module.js 15:0-63
        @ ./src/app/app.module.ngfactory.js
        @ ./src/app/main.ts
            at new BuildError
        (/Users/sjbwybls/Documents/gitrepo/ionic-ng2-stompjs/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
            at
        /Users/sjbwybls/Documents/gitrepo/ionic-ng2-stompjs/node_modules/@ionic/app-scripts/dist/preprocess.js:18:21
            at <anonymous>
            at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by kum-deepak** [comment]
Currently I do not have a satisfactory solution. 

The following workaround worked for me:

- Copied the entire code into src/app
- Reverted the changes in tsconfig (made it same as previous commit)
- Changed references to associated classes to paths of copied files.

At this point got a build issue in sockjs-client.

Looking at your code, it seems you are using RabbitMQ. If you are then please stop using SockJS and instead use WebSocket directly.

Additionally I will suggest to ask a question in ionic project to find out how to use a library distributed as .ts files.

**Comment by kum-deepak** [comment]
I am also going to try https://github.com/dherges/ng-packagr to see if that helps in packaging.
