### ISSUE TITLE
node_modules/@stomp/ng2-stompjs/index.ts is missing from the TypeScript compilation.

### ISSUE THREAD

**Issue by Taisho** [stomp-js/ng2-stompjs#49]
I needed to perform an update of all angular modules for my project (Because of 'Version mismatching' error). Then I had to update angular-cli. After that, running `ng serve` yielded this error

> ERROR in ./node_modules/@stomp/ng2-stompjs/index.ts
> Module build failed: Error: /home/tichomir/web-technologies/angularjs/rota-second/client/node_modules/@stomp/ng2-stompjs/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
> The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
>     at AngularCompilerPlugin.getCompiledFile (/home/tichomir/web-technologies/angularjs/rota-second/client/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:653:23)
>     at plugin.done.then (/home/tichomir/web-technologies/angularjs/rota-second/client/node_modules/@ngtools/webpack/src/loader.js:467:39)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
>  @ ./src/app/app.module.ts 23:20-49
>  @ ./src/main.ts
>  @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by Taisho** [comment]
Updating `@stomp/ng2-stompjs` to `0.6.2` removed the error
