### ISSUE TITLE
error looking for websocket.js

### ISSUE THREAD

**Issue by faisalloe** [stomp-js/ng2-stompjs#68]
using angular5 with typescript
I am getting following error, does it have a dependency or any other library ?

```
git_source_code/testme/web/src/main/webapp/node_modules/websocket/lib/websocket.js


(index):29 Error: (SystemJS) XHR error (404) loading https://localhost:8443/testme/websocket
	Error: XHR error (404) loading https://localhost:8443/testme/websocket
	    at XMLHttpRequest.wrapFn (https://localhost:8443/testme/node_modules/zone.js/dist/zone.js:1166:39)
	    at ZoneDelegate.invokeTask (https://localhost:8443/testme/node_modules/zone.js/dist/zone.js:421:31)
	    at Zone.runTask (https://localhost:8443/testme/node_modules/zone.js/dist/zone.js:188:47)
	    at ZoneTask.invokeTask [as invoke] (https://localhost:8443/testme/node_modules/zone.js/dist/zone.js:496:34)
	    at invokeTask (https://localhost:8443/testme/node_modules/zone.js/dist/zone.js:1517:14)
	    at XMLHttpRequest.globalZoneAwareCallback (https://localhost:8443/testme/node_modules/zone.js/dist/zone.js:1543:17)
	Error loading https://localhost:8443/testme/websocket as "websocket" from https://localhost:8443/testme/node_modules/@stomp/stompjs/index.js
```
	following is my systemjs.config.js entry

Systemjs.config.js
	------------------
	
	```
System.config({

		..
		
        '@stomp/ng2-stompjs':'npm:@stomp/ng2-stompjs/bundles/ng2-stompjs.umd.js',
            '@stomp':'npm:@stomp',
            
        ..    
	
		packages: {
		..
		'@stomp': {defaultExtension: 'js'}
		..
		}
	
	
	})
```

**Comment by kum-deepak** [comment]
This package depends only on `@stomp/stompjs`. That library in turn lists (https://github.com/stomp-js/stomp-websocket/blob/master/package.json) `websocket` as optional dependency.

`@stomp/stompjs` needs `websocket` only when it is run in nodejs environment and not needed when run in a browser.

I have never used SystemJS. So, may not be able to help quickly. See if you can find a way for SystemJS to consider that `websocket` is not needed.

If you want me to have a look, please create a minimal application that demonstrates the issue and share on GitHub.

You can check a quick work around by installing `"websocket": "^1.0.24"` as a dependency.

**Comment by kum-deepak** [comment]
With a caution that I do not use SystemJS - https://stackoverflow.com/questions/37403990/how-to-tell-systemjs-to-ignore-an-import technique might help.

**Comment by kum-deepak** [comment]
I will close it in few days 😄

**Comment by faisalloe** [comment]
I was able to fix. Will post my solution here in few mins

**Comment by kum-deepak** [comment]
@faisalloe any chance you would be able to post what worked for you. 😃
